### ISSUE TITLE
bro when i'm running nothing happened " why??

### ISSUE THREAD

**Issue by Stakingsoup** [ignite7/quickaccount#1]

**Comment by kingsalman99** [comment]
![Screenshot_2020-08-04-03-07-11-13_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/58569784/89223371-dd568380-d600-11ea-8a12-3a27618dc051.jpg)

**Comment by kingsalman99** [comment]
thats it bro

**Comment by ignite7** [comment]
I realized that too, it's a simple mistake I committed because I forgot to delete a line of code when I was testing it in the file `app/services.py` in the line `78. options.add_argument('--headless')` delete this line from your code and it gonna fix and shows the window to complete the **captcha** or do `git pull https://github.com/ignite7/quickaccount.git` I've fixed the error in my last commit.

**Comment by Stakingsoup** [comment]
> thats it bro

Thanks working
